---
version: '3.6'
services:
  # postgres:
  #   image: postgres:12
  #   restart: always
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  #     POSTGRES_DB: ${DATABASE_NAME}
  #   ports:
  #     - '${DATABASE_PORT}:5432'
  graphql-engine:
    image: hasura/graphql-engine:v1.3.2.cli-migrations-v2
    ports:
      - '${HASURA_GRAPHQL_PORT}:8080'
    # network_mode: 'host'
    # depends_on:
    #   - 'postgres'
    restart: always
    volumes:
      - ./migrations:/migrations
      - ./metadata:/metadata
    environment:
      API_URL: $API_URL
      HASURA_GRAPHQL_DATABASE_URL: $DATABASE_URL
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: $HASURA_GRAPHQL_ENABLED_LOG_TYPES
      HASURA_GRAPHQL_ADMIN_SECRET: $HASURA_GRAPHQL_ADMIN_SECRET
      HASURA_GRAPHQL_JWT_SECRET: $HASURA_GRAPHQL_JWT_SECRET
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_MIGRATIONS_DIR: $HASURA_GRAPHQL_MIGRATIONS_DIR
      HASURA_GRAPHQL_METADATA_DIR: $HASURA_GRAPHQL_METADATA_DIR
      HASURA_GRAPHQL_FUNCTIONS_URL: $HASURA_GRAPHQL_FUNCTIONS_URL
      # use `hasura console --admin-secret $HASURA_GRAPHQL_ADMIN_SECRET` instead
      # so it creates migrations
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false' # set to "false" to disable console
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
